name: CwlPdfApp

options:
  minimumXcodeGenVersion: 2.44.0
  usesTabs: true
  tabWidth: 4
  indentWidth: 4
  schemePathPrefix: ../
  localPackagesGroup: ""
  groupOrdering:
    - order:
        - CwlPdfApp
        - CwlPdfLib
        - Products

settings:
  base:
    SWIFT_APPROACHABLE_CONCURRENCY: YES
    SWIFT_VERSION: 6.0

packages:
  CwlPdfLib:
    path: .

targets:
  CwlPdfApp:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: CwlPdfApp
    dependencies:
      - package: CwlPdfLib
        product: CwlPdfView
    info:
      path: CwlPdfApp/Info.plist
      properties:
        CFBundleDocumentTypes:
          - CFBundleTypeName: PDF Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - com.adobe.pdf
        NSPrincipalClass: NSApplication
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: CwlPdfApp
        PRODUCT_BUNDLE_IDENTIFIER: com.mattgallagher.CwlPdfApp
        INFOPLIST_FILE: CwlPdfApp/Info.plist
        DEVELOPMENT_ASSET_PATHS: CwlPdfApp/Preview.xcassets
        ENABLE_PREVIEWS: YES

schemes:
  CwlPdfApp:
    build:
      targets:
        CwlPdfApp: build
    run:
      config: Release
    test:
      testPlans:
        - path: CwlPdfApp/CwlPdfApp.xctestplan
